name: mint-latest Developement Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Mint
      run: |
        sudo apt-get update

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.6
        install-deps: 'true'
        modules: 'qtcharts'

    - name: Where Am I
      run: |
        pwd
        ls -l
        lscpu

    - name: Versions
      run: g++ --version

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cd src
        cmake -B ${{github.workspace}}/src/build -DQTVERSION=QT6 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: |
        cd src
        cmake --build ${{github.workspace}}/src/build --config ${{env.BUILD_TYPE}} --target seergdb --parallel `grep -c processor /proc/cpuinfo`

    - name: Tar
      run: |
        cd src/build
        cp ../../LICENSE .
        cp ../../CHANGELOG.md .
        tar zcvf seergdb.tar.gz LICENSE CHANGELOG.md seergdb

    - name: List Results
      run: |
        cd src
        ls -l build/

    - name: Build Mint Developement Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "mint-latest"
        prerelease: true
        title: "Mint Development Release"
        files: |
          src/build/seergdb.tar.gz

  debian-pkg:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install devscripts build-essential dpkg-dev equivs
        sudo mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control

    - name: Build Debian package
      run:  dpkg-buildpackage --unsigned-source --unsigned-changes

    - name: Upload debian package Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "debian-pkg-latest"
        prerelease: true
        title: "Mint Package Release"
        files: |
          ../seergdb_*_amd64.deb
